### PR TITLE
Force compression for JS files

### PR DESCRIPTION
**Pull request by jacobbednarz**
I have no idea why the mime-type gem doesn't always pick up the correct
content type and set the gzipping correctly however this hammer approach
will fix it in the mean time until this gem is replaced.

### CODE REVIEW

**Comment by jordanlewiz** [comment]
LGTM, however I have limited limited understanding of static_sync

**Comment by jordanlewiz** [comment]
@jacobbednarz it also seems CSS is not being gzipped. Do you think this issue is actually MIME type related?

calibre-22-12

**Comment by jordanlewiz** [comment]
CSS and JS Gzipping appears fixed now 🎉 
screen shot 2016-12-23 at 8 50 49 am

**Comment by jacobbednarz** [comment]
moved this logic to our CDN instead. seemed silly to have a tool telling our CDN what it should be compressing.

**Pull request closed without merging**
